### PR TITLE
feat(TransferFunctionWidget): swap in itk-viewer-transfer-function-editor

### PR DESCRIPTION
**Pull request by PaulHax**
Put prettier config in a standard place.

### CODE REVIEW

**Review by bnmajor — APPROVED** [review]
This is looking great, thank you! Just need to figure out why the firefox tests are failing and get that sorted... I'm happy to look at this as well, probably this afternoon or tomorrow morning.

**Comment by PaulHax** [comment]
Looks like there is a bug in the transfer function editor I will fix.

**Comment by PaulHax** [comment]
@bnmajor Tests all better now =)

**Comment by bnmajor** [comment]
@PaulHax Thanks!

**Pull request merged**
